
CREATE TABLESPACE CASAMENTO
DATAFILE 'C:\Users\Shadow\Documents\TCC\UNIQ PROJECT\TCC_CODIGO - Casamento\02.DBF'
SIZE 1M AUTOEXTEND ON MAXSIZE 10M ONLINE;

CREATE USER CASAMENTO IDENTIFIED BY 123456
DEFAULT TABLESPACE CASAMENTO
TEMPORARY TABLESPACE TEMP
ACCOUNT UNLOCK;

drop user CASAMENTO;
Grant all privileges to  CASAMENTO;

DROP TABLE TB_COMPRA
CREATE TABLE TB_COMPRA(
ID_COMPRA NOT NULL,
VALOR_COMPRA NOT NULL,
QUANTIDADE_COMPRA NOT NULL,
FORNECEDOR_COMPRA NOT NULL,
);

DROP TABLE TB_PRODUTO;

CREATE TABLE TB_PRODUTO(
ID_PRODUTO INTEGER PRIMARY KEY NOT NULL,
QUANTIDADE_PRODUTO INT NOT NULL,
NOME_PRODUTO VARCHAR2 (20) NOT NULL,
VALOR_PRODUTO DOUBLE NOT NULL,
CARACTERISTICAS_PRODUTO VARCHAR2(500)
);

DROP TABLE TB_FUNCIONARIO;

CREATE TABLE TB_FUNCIONARIO(
ID_FUNC INTEGER PRIMARY KEY NOT NULL,
NOME_FUNC varchar2 (100) NOT NULL,
CPF_FUNC VARCHAR2 (11) NOT NULL,
ENDERECO_FUNC VARCHAR2 (100) NOT NULL,
SEXO_FUNC VARCHAR2 (9) NOT NULL,
EMAIL_FUNC VARCHAR2 (100) NOT NULL,
SALARIO_FUNC DOUBLE NOT NULL,
CARGO_FUNC VARCHAR2 (50) NOT NULL
);

DROP TABLE TB_VENDA;

CREATE TABLE TB_VENDA(
ID_VENDA NOT NULL,
ID_CLIENTE NOT NULL,
ID_FUNC NOT NULL,
ID_PRODUTO NOT NULL,
VALOR_VENDA DOUBLE NOT NULL,
QUANTIDADE_VENDA INT NOT NULL,
PAGAMENTO_VENDA VARCHAR2 (14) NOT NULL,
CONSTRAINT FK_TBCLIENTE FOREIGN KEY (ID_CLIENTE) REFERENCES TB_CLIENTE(Id_Cliente),
CONSTRAINT FK_TBFUNC FOREIGN KEY (ID_FUNC) REFERENCES TB_FUNCIONARIO(ID_FUNC),
CONSTRAINT FK_TBPRODUTO FOREIGN KEY (ID_PRODUTO) REFERENCES TB_PRODUTO(ID_PRODUTO),
CONSTRAINT PK_VENDA PRIMARY KEY (ID_VENDA, ID_CLIENTE, ID_FUNC, ID_PRODUTO,)
);

DROP TABLE TB_CLIENTE;

CREATE TABLE  TB_CLIENTE(
Id_Cliente INTEGER PRIMARY KEY NOT NULL,
Nome_Cliente VARCHAR2(100) NOT NULL,
Nasc_Cliente VARCHAR2(10) NOT NULL,
Telefone_Cliente VARCHAR2(13) NOT NULL,
CPF_Cliente VARCHAR2(14) NOT NULL,
Endereço_Cliente VARCHAR2(100) NOT NULL,
Email_Cliente VARCHAR2(100) NOT NULL,
Senha_Cliente VARCHAR2(20) NOT NULL
);

